services:
  - type: web
    plan: free
    name: mysite
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn mysite.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: "obn_app.settings"
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        value: "sqlite:///db.sqlite3"
