services:
  - type: web
    plan: free
    name: mysite
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn obn_app.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: "obn_app.settings"
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        value: "sqlite:///db.sqlite3"
