# Generated by Django 5.1.1 on 2024-09-13 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_file_uploaded_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='P190Line',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linename', models.IntegerField()),
                ('eastings1', models.FloatField()),
                ('northings1', models.FloatField()),
                ('latitude1', models.FloatField()),
                ('longitude1', models.FloatField()),
                ('eastings2', models.FloatField()),
                ('northings2', models.FloatField()),
                ('latitude2', models.FloatField()),
                ('longitude2', models.FloatField()),
            ],
        ),
    ]
