# Generated by Django 5.1.1 on 2024-09-14 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0003_p190line'),
    ]

    operations = [
        migrations.AddField(
            model_name='p190line',
            name='shotpoint1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='p190line',
            name='shotpoint2',
            field=models.IntegerField(default=0),
        ),
    ]
