# Generated by Django 5.1.1 on 2024-09-15 04:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0004_p190line_shotpoint1_p190line_shotpoint2'),
    ]

    operations = [
        migrations.CreateModel(
            name='SequenceFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preplot_number', models.IntegerField()),
                ('type', models.IntegerField()),
                ('pass_number', models.IntegerField()),
                ('sequence_number', models.IntegerField()),
                ('filename', models.CharField(max_length=255)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='P190Line',
            new_name='PreplotLine',
        ),
        migrations.CreateModel(
            name='GunEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shotpoint', models.IntegerField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('easting', models.FloatField()),
                ('northing', models.FloatField()),
                ('julian_day', models.IntegerField()),
                ('time', models.TimeField()),
                ('gun_depth', models.FloatField()),
                ('p190_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.sequencefile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EchosounderEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shotpoint', models.IntegerField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('easting', models.FloatField()),
                ('northing', models.FloatField()),
                ('julian_day', models.IntegerField()),
                ('time', models.TimeField()),
                ('depth', models.FloatField()),
                ('p190_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.sequencefile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SourceEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shotpoint', models.IntegerField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('easting', models.FloatField()),
                ('northing', models.FloatField()),
                ('julian_day', models.IntegerField()),
                ('time', models.TimeField()),
                ('depth', models.FloatField()),
                ('avg_latitude', models.FloatField()),
                ('avg_longitude', models.FloatField()),
                ('avg_easting', models.FloatField()),
                ('avg_northing', models.FloatField()),
                ('p190_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.sequencefile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VesselEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shotpoint', models.IntegerField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('easting', models.FloatField()),
                ('northing', models.FloatField()),
                ('julian_day', models.IntegerField()),
                ('time', models.TimeField()),
                ('depth', models.FloatField()),
                ('p190_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.sequencefile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
