# Generated by Django 5.1.1 on 2024-09-17 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0007_rename_sequence_file_sequencefiledetail_linename'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sequencefiledetail',
            old_name='mean_e',
            new_name='mean_lat',
        ),
        migrations.RenameField(
            model_name='sequencefiledetail',
            old_name='mean_n',
            new_name='mean_lon',
        ),
        migrations.RenameField(
            model_name='sequencefiledetail',
            old_name='ze1',
            new_name='zlat1',
        ),
        migrations.RenameField(
            model_name='sequencefiledetail',
            old_name='ze2',
            new_name='zlat2',
        ),
        migrations.RenameField(
            model_name='sequencefiledetail',
            old_name='ze3',
            new_name='zlat3',
        ),
        migrations.RenameField(
            model_name='sequencefiledetail',
            old_name='zn1',
            new_name='zlon1',
        ),
        migrations.RenameField(
            model_name='sequencefiledetail',
            old_name='zn2',
            new_name='zlon2',
        ),
        migrations.RenameField(
            model_name='sequencefiledetail',
            old_name='zn3',
            new_name='zlon3',
        ),
    ]
