# Generated by Django 5.1.1 on 2024-09-17 02:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0008_rename_mean_e_sequencefiledetail_mean_lat_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sequencefiledetail',
            name='linename',
        ),
        migrations.AddField(
            model_name='sequencefiledetail',
            name='sequence_file',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='details', to='planner.sequencefile'),
        ),
        migrations.AlterField(
            model_name='sequencefile',
            name='linename',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
