# Generated by Django 5.1.1 on 2024-09-22 21:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0009_remove_sequencefiledetail_linename_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Points',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linename', models.IntegerField()),
                ('shotpoint', models.IntegerField()),
                ('easting', models.FloatField()),
                ('northing', models.FloatField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('preplotline', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='planner.preplotline')),
            ],
        ),
        migrations.DeleteModel(
            name='Point',
        ),
    ]
